config/routes.rb
Rails.application.routes.draw do
  resources :business_customers
  devise_for :customers
  devise_for :staffs
  resources :points
  resources :customers
  resources :promotions

  
  resources :businesses do
    resources :staffs
  end

  root 'businesses#index'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
 
  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
    @staffs = Staff
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @staffs = Staff.where(business_id: @business.id).order(:id)
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:company_name, :company_type)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_area :company_name %>
  </div>
  <div class="field">
    <%= f.label :company_type %><br>
    <%= f.text_area :company_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Businesses</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Company type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.company_name %></td>
        <td><%= business.company_type %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Staff', new_business_staff_path(business) %></td>
        <td><%= link_to 'Add New Customer', new_business_customer_path(business) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @business.company_name %>
</p>

<p>
  <strong>Company type:</strong>
  <%= @business.company_type %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>