config/routes.rb
Rails.application.routes.draw do
  resources :business_customers
  devise_for :customers
  devise_for :staffs
  resources :points
  resources :customers
  resources :promotions

  
  resources :businesses do
    resources :staffs
  end

  root 'businesses#index'

end

app/views/layouts/_header.html.erb
 <!-- Fixed navbar -->
    <nav class="navbar navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-responsive-collapse" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
        <div id="navbar" class="navbar-collapse collapse navbar-responsive-collapse">
          <div class="header-inner"
             <a id="header-logo" class="navbar-brand">
                <%= image_tag (""), class: "header_image pull-left" %>
          </div>
                <a class="navbar-brand" href="/businesses">Business Woohoo</a>
          </form>
          <ul class="nav navbar-nav navbar-right">
            
            <li class="<%= header_active("businesses", "index") %>"><%= link_to "Home", root_path %></li>
            <li class="<%= header_active("promotions","index") %>"><%= link_to "Promotions", promotions_path %></li>
            <% if staff_signed_in? %>
                <li>
                  <%= link_to('Logout', destroy_staff_session_path, :method => :delete) %>        
                </li>
            <% else %>
                <li>
                  <%= link_to('Login', new_staff_session_path)  %>  
                </li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/_shim.html.erb
 <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Business Promotions</title>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= render 'layouts/shim' %>
    <%= csrf_meta_tags %>
    <%= yield :js_html %>
    <script>
    	<%= yield :js %>
    </script>

</head>

  <body>
  	<%= render 'layouts/header' %>
    
    <div class="container">
    <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type%>"><%= message %></div>
    <% end %>
     <%= yield %>
     
    </div> <!-- /container -->

      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>